"""SPEC.md §10's reconciliation fault-suite rows, run against a feed
generated by `scripts.gen_feed.generate_feed` -- the same drift-injection
code path `scripts/gen_feed.py`'s CLI uses, not hand-rolled per test.
"""

import random
from datetime import UTC, date, datetime
from typing import Any

import pytest
from httpx import AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from scripts.gen_feed import DriftConfig, FeedTransaction, generate_feed

pytestmark = [pytest.mark.integration, pytest.mark.fault]


async def _create_account(client: AsyncClient, **kwargs: object) -> dict[str, Any]:
    payload: dict[str, object] = {
        "name": "Account",
        "type": "asset",
        "currency": "USD",
        "allow_negative": False,
    }
    payload.update(kwargs)
    response = await client.post("/v1/accounts", json=payload)
    assert response.status_code == 201, response.text
    return dict(response.json())


async def _post(
    client: AsyncClient, cash: str, revenue: str, amount: int, ref: str
) -> dict[str, Any]:
    response = await client.post(
        "/v1/transactions",
        json={
            "entries": [
                {"account_id": cash, "direction": "debit", "amount": amount, "currency": "USD"},
                {"account_id": revenue, "direction": "credit", "amount": amount, "currency": "USD"},
            ],
            "external_ref": ref,
        },
    )
    assert response.status_code == 201, response.text
    return dict(response.json())


async def _backdate(engine: AsyncEngine, transaction_id: str, days: int) -> None:
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "UPDATE transactions"
                " SET created_at = now() - make_interval(days => :d)"
                " WHERE id = :id"
            ),
            {"d": days, "id": transaction_id},
        )


async def _run(client: AsyncClient, key: str) -> dict[str, Any]:
    response = await client.post("/v1/reconciliation/runs", headers={"Idempotency-Key": key})
    assert response.status_code == 201, response.text
    return dict(response.json())


async def _findings(client: AsyncClient, run_id: str) -> list[dict[str, Any]]:
    response = await client.get(f"/v1/reconciliation/runs/{run_id}/findings")
    return list(response.json()["items"])


async def test_dropped_line_produces_missing_settlement(
    app_client: AsyncClient, db_engine: AsyncEngine
) -> None:
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    txn = await _post(app_client, cash, revenue, 1000, "ref-drop")
    await _backdate(db_engine, str(txn["id"]), days=3)

    feed_txns = [
        FeedTransaction(
            external_ref="ref-drop", amount=1000, currency="USD", value_date=date(2020, 1, 1)
        )
    ]
    lines = generate_feed(feed_txns, DriftConfig(drop_rate=1.0), random.Random(0))
    assert lines == []  # the drift itself: the feed contains nothing

    run = await _run(app_client, "drop-run")
    findings = await _findings(app_client, str(run["id"]))
    assert len(findings) == 1
    assert findings[0]["finding_type"] == "missing_settlement"


async def test_duplicated_line_produces_duplicate_settlement_no_double_ledger_effect(
    app_client: AsyncClient,
) -> None:
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    await _post(app_client, cash, revenue, 1000, "ref-double")
    value_date = datetime.now(UTC).date()

    feed_txns = [
        FeedTransaction(
            external_ref="ref-double", amount=1000, currency="USD", value_date=value_date
        )
    ]
    lines = generate_feed(feed_txns, DriftConfig(duplicate_rate=1.0), random.Random(0))
    assert len(lines) == 2

    for line in lines:
        await app_client.post(
            "/v1/settlements/ingest",
            json={
                "lines": [
                    {
                        "external_ref": line.external_ref,
                        "amount": line.amount,
                        "currency": line.currency,
                        "value_date": line.value_date.isoformat(),
                        "raw": line.raw,
                    }
                ]
            },
        )

    run = await _run(app_client, "dup-run")
    findings = await _findings(app_client, str(run["id"]))
    assert any(f["finding_type"] == "duplicate_settlement" for f in findings)

    cash_bal = (await app_client.get(f"/v1/accounts/{cash}")).json()
    assert cash_bal["balance"] == 1000  # exactly once, not twice


async def test_perturbed_amount_auto_resolves_under_threshold(app_client: AsyncClient) -> None:
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    await _create_account(app_client, name="Suspense", allow_negative=True, is_suspense=True)
    await _create_account(app_client, name="Clearing", allow_negative=True, is_clearing=True)
    await _post(app_client, cash, revenue, 1000, "ref-perturb")
    value_date = datetime.now(UTC).date()

    feed_txns = [
        FeedTransaction(
            external_ref="ref-perturb", amount=1000, currency="USD", value_date=value_date
        )
    ]
    # perturb_max_minor 5 -- comfortably under the default 500-minor-unit
    # auto-resolve threshold, so this must auto_resolve, not stay unresolved.
    lines = generate_feed(
        feed_txns, DriftConfig(perturb_rate=1.0, perturb_max_minor=5), random.Random(0)
    )
    line = lines[0]
    assert line.amount != 1000

    await app_client.post(
        "/v1/settlements/ingest",
        json={
            "lines": [
                {
                    "external_ref": line.external_ref,
                    "amount": line.amount,
                    "currency": line.currency,
                    "value_date": line.value_date.isoformat(),
                    "raw": line.raw,
                }
            ]
        },
    )
    run = await _run(app_client, "perturb-run")
    findings = await _findings(app_client, str(run["id"]))
    finding = next(f for f in findings if f["finding_type"] == "amount_mismatch")
    assert finding["resolution"] == "auto_resolved"


async def test_perturbed_amount_over_threshold_stays_unresolved(app_client: AsyncClient) -> None:
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    await _post(app_client, cash, revenue, 1000, "ref-big-perturb")
    value_date = datetime.now(UTC).date()

    feed_txns = [
        FeedTransaction(
            external_ref="ref-big-perturb", amount=1000, currency="USD", value_date=value_date
        )
    ]
    lines = generate_feed(
        feed_txns, DriftConfig(perturb_rate=1.0, perturb_max_minor=10_000), random.Random(3)
    )
    line = lines[0]

    await app_client.post(
        "/v1/settlements/ingest",
        json={
            "lines": [
                {
                    "external_ref": line.external_ref,
                    "amount": line.amount,
                    "currency": line.currency,
                    "value_date": line.value_date.isoformat(),
                    "raw": line.raw,
                }
            ]
        },
    )
    run = await _run(app_client, "big-perturb-run")
    findings = await _findings(app_client, str(run["id"]))
    finding = next(f for f in findings if f["finding_type"] == "amount_mismatch")
    delta = finding["delta_amount"]
    if abs(delta) <= 500:
        pytest.skip("perturbation landed under the threshold for this seed")
    assert finding["resolution"] == "unresolved"


async def test_transaction_after_cutoff_is_in_flight_not_missing(app_client: AsyncClient) -> None:
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    await _post(app_client, cash, revenue, 1000, "ref-cutoff")

    # Not backdated -- a transaction posted moments ago is inside the
    # 24h cutoff lag by construction, and the feed reports nothing for it.
    run = await _run(app_client, "cutoff-run")
    findings = await _findings(app_client, str(run["id"]))
    assert len(findings) == 1
    assert findings[0]["finding_type"] == "in_flight"
    assert findings[0]["resolution"] == "suppressed"


async def test_rerun_over_unchanged_window_reports_no_new_findings(
    app_client: AsyncClient, db_engine: AsyncEngine
) -> None:
    """The SPEC.md §10 row the design review's fix targets directly: a
    second run over the same window must not re-report (or, worse,
    re-adjust) drift the first run already recorded."""
    cash = str((await _create_account(app_client, name="Cash"))["id"])
    revenue = str((await _create_account(app_client, name="Revenue", type="revenue"))["id"])
    await _create_account(app_client, name="Suspense", allow_negative=True, is_suspense=True)
    await _create_account(app_client, name="Clearing", allow_negative=True, is_clearing=True)

    dropped_txn = await _post(app_client, cash, revenue, 1000, "ref-open-drift")
    await _backdate(db_engine, str(dropped_txn["id"]), days=3)

    await app_client.post(
        "/v1/settlements/ingest",
        json={
            "lines": [
                {
                    "external_ref": None,
                    "amount": 250,
                    "currency": "USD",
                    "value_date": datetime.now(UTC).date().isoformat(),
                    "raw": {},
                }
            ]
        },
    )

    run1 = await _run(app_client, "rerun-1")
    assert run1["findings_by_type"]["created"] == {
        "missing_settlement": 1,
        "unexpected_settlement": 1,
    }

    run2 = await _run(app_client, "rerun-2")
    assert run2["findings_by_type"]["created"] == {}
    # "observed" still reports the open missing_settlement -- it just isn't
    # new.
    assert run2["findings_by_type"]["observed"].get("missing_settlement") == 1
